# Generated by Django 3.2.8 on 2021-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(help_text='Ingrese el Título', max_length=200),
        ),
    ]
